#!/usr/bin/env python3

IMAGES = [
    {
        "name": "trusty",
        "base_image": "ubuntu:trusty-20191217",
    },
    {
        "name": "xenial",
        "base_image": "ubuntu:xenial-20200916",
    },
    {
        "name": "bionic",
        "base_image": "ubuntu:bionic-20200921",
    },
    {
        "name": "focal",
        "base_image": "ubuntu:focal-20200916",
    },
    {
        "name": "groovy",
        "base_image": "ubuntu:groovy-20200921",
    },
]

WARNING = (
    "# Generated by generate.py.\n"
    "# DO NOT EDIT!\n\n"
)

if __name__ == '__main__':
    import os
    import jinja2

    os.chdir(os.path.dirname(os.path.realpath(__file__)))

    loader = jinja2.FileSystemLoader(searchpath="./templates")
    env = jinja2.Environment(loader=loader, keep_trailing_newline=True)

    for image in IMAGES:
        tpl = env.get_template(f'{image["name"]}.tpl')
        with open(f'{image["name"]}.Dockerfile', 'w') as f:
            f.write(WARNING)
            f.write(tpl.render(**image))
